on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      #----------------------------------------------
      #       Setup node & ganache-cli
      #----------------------------------------------
      - uses: actions/setup-node@v1
      - name: Install Ganache CLI and Solidity compiler
        run: npm install -g ganache-cli solc
      - name: Run Ganache CLI in Background
        run: ganache-cli --networkId 1337 -m "hamster coin cup brief quote trick stove draft hobby strong caught unable" &
      # Test and build
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: build
